build(HOT9)add database schema
hirotachi/bref4-holiday-hotel pull request #4
Opened 2022-10-13 08:21 UTC by Raikonerr

2022-10-13 18:55 UTC, daalimouhcine approved these changes

2022-10-14 08:10 UTC, hirotachi approved these changes, later dismissed

2022-10-14 08:24 UTC, daalimouhcine requested changes
if possible change the naming of table extra to extras, also for table reservation_extra.

2022-10-14 08:47 UTC, hirotachi approved these changes

2022-10-14 11:07 UTC, daalimouhcine approved these changes

2022-10-14 11:08 UTC, merged